name: GronkhPlugin
version: 1.0.0
description: Plugin für die Gronkh Community Server Bewerbung
main: main.Loader

commands:
  hug:
    description: Hug a player
    usage: /<command> PlayerName
  keepday:
    description: Tag-Nacht-Wechsel ein- und ausschalten
    usage: /<command>